# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89b81766fc25921f87e18fbee71860d75dc76c3c365c24bbb5b1bcfbb414e8f11a6982d09ebabf31a1ded02f816cc466d444a6808a9e451f460b5c4bf298b13f

test:
  secret_key_base: 62f55a810d0a34e6faddc0a86d2bb0102b8555d9c89230b2b57fa325129dbf23b5a7614efba81571fe7d0416524fd4f5832d15aa2aba3a94b21023177d8f84ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
